# Use the official Python image as a parent image
FROM python:3.11.9-bullseye

# Set the working directory in the container
WORKDIR /app

# Copy the script into the container at /app
COPY greet2.py /app

# Run img2vid.py when the container launches with ENTRYPOINT
ENTRYPOINT ["python", "greet2.py"]